--- 
- 
  become: true
  hosts: all
  name: "ansible playbook"
  tasks: 
    - 
      apt: 
        name: apache2
        state: present
        update_cache: true
      name: "apache install"
        