---
- name: deploy spc as linux service
  hosts: appserver
  become: yes
  tasks:
   - name: update n instal java
     apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
   - name: creating dir for spc
     file:
        path: /usr/share/springpetclinic
        state: directory
   - name: download spc from net
     get_url:
        url:  https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
   - name: creating springbootuser
     user:
        name: springbootuser
        password: springbootuser
        state: present
   - name: giving 500 ownership ryts to new user
     file:
        path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
        owner: springbootuser
        mode: '500'
        state: file
   - name: copying spc file to node
     copy:
        dest: /etc/systemd/system/springpetclinic.service
        src: springpetclinic.service
   - name: enable n start spc service
     systemd:
        name: springpetclinic.service
        enabled: yes
        state: started